spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/hierbas_db
    username: root
    password: password
  application:
    name: registro-hierbas

server:
  port: 8080

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.plantas: DEBUG
    org.springframework.r2dbc: DEBUG